title: CS_BS
description: >- # this means to ignore newlines until "baseurl:"
  Attention CSUF computer science majors! Are you
  tired of not learning enough from your computer
  science professors? Don’t sweat it! Introducing
  CS-BS.com. This website allows the chance for all
  students taking CS classes to drop URL’s or other
  resources that might be helpful for other students
  to view and to hopefully pass their classes!
baseurl: "/cs-bs" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: pmarsceill/just-the-docs

# Just the docs Configuration settings
# For a list of all settings check https://pmarsceill.github.io/just-the-docs/docs/configuration/

search_enabled: true

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Aux links for the upper right navigation
aux_links:
  "CS-BS on GitHub":
    - "//github.com/BuiTheBoi/cs-bs"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Define Jekyll collections
collections:
  # Define a collection named "subjects", its documents reside in the "_subjects" directory
  subjects:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "subjects" collection
    subjects:
      # Give the collection a name
      name: Subjects
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false

plugins:
  - jekyll-feed
